### ISSUE TITLE
How to get the collider to move for animation ?

### ISSUE THREAD

**Issue by Curiosity10001** [GSaillenfest/Module_BeatEmUp#13]

**Comment by Curiosity10001** [comment]
see projects issues/action list on project page

**Comment by GSaillenfest** [comment]
Other solution to try later :
http://answers.unity.com/answers/1810252/view.html
![image](https://user-images.githubusercontent.com/104986291/191234142-9ce347db-a5c9-4fee-8a7b-0a6921574f3f.png)
